Convert Swift client test to Github Actions CI
google/myanmar-tools pull request #81
Opened 2021-05-21 23:32 UTC by echeran

2021-05-22 01:14 UTC, sffc requested changes
Thanks!

2021-05-22 01:14 UTC, sffc commented on .github/workflows/mynmr_tools_ci.yml
> +      - run: make client-swift
```suggestion
      - run: make client-swift-test
```

2021-05-25 00:51 UTC, sffc approved these changes
@echeran Can you resolve the issue with the Google CLA?

2021-05-25 16:07 UTC, echeran commented
@sffc My side is now good, it looks like what is left is your unicode.org email address needs to be added to the CLA.

2021-05-27 04:02 UTC, merged